# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_model.majority_label_voter.ipynb (unless otherwise specified).

__all__ = ['MajorityLabelVoter']

# Cell
from fastai2.basics import *

# Cell
class MajorityLabelVoter(Module):
    def forward(self, x):
        preds = []
        for row in x:
            row = row[row!=0]
            if row.numel() == 0: preds.append(0)
            else:                preds.append(row.mode().values.item())
        return tensor(preds).to(x.device)