# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"instantiate": "00_core.ipynb",
         "split_batch": "00_core.ipynb",
         "TfmdLists.__init__": "00_core.ipynb",
         "TfmdLists.cache": "00_core.ipynb",
         "TfmdLists.__getitem__": "00_core.ipynb",
         "AttrProxy": "00_core.ipynb",
         "add_attr": "00_core.ipynb",
         "maintain_labels": "00_core.ipynb",
         "Pipeline.__init__": "00_core.ipynb",
         "subscribe": "00_core.ipynb",
         "UniqueList": "02_labeller.core.ipynb",
         "Labeller": "02_labeller.core.ipynb",
         "Labeller.find": "02_labeller.core.ipynb",
         "tasks_labels": "02_labeller.core.ipynb",
         "LabelMetric": "02a_labeller.metrics.ipynb",
         "ValidLabelMetric": "02a_labeller.metrics.ipynb",
         "Coverage": "02a_labeller.metrics.ipynb",
         "Polarity": "02a_labeller.metrics.ipynb",
         "CountCorrect": "02a_labeller.metrics.ipynb",
         "CountIncorrect": "02a_labeller.metrics.ipynb",
         "LabelAccuracy": "02a_labeller.metrics.ipynb",
         "defaults.labeller_metrics": "02a_labeller.metrics.ipynb",
         "Labeller.__init__": "02a_labeller.metrics.ipynb",
         "Labeller.summary": "02a_labeller.metrics.ipynb",
         "MajorityLabelVoter": "03_model.majority_label_voter.ipynb",
         "Tokens": "05_text.core.ipynb",
         "Tokenizer.__call__": "05_text.core.ipynb",
         "WordLabeller": "06_text.labellers.ipynb"}

modules = ["core.py",
           "labeller/core.py",
           "labeller/metrics.py",
           "models/majority_label_voter.py",
           "text/core.py",
           "text/labellers.py"]

doc_url = "https://lgvaz.github.io/lazylabel/"

git_url = "https://github.com/lgvaz/lazylabel/tree/master/"

def custom_doc_links(name): return None
