# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_data.transforms.ipynb (unless otherwise specified).

__all__ = ['TaskLabels', 'Categorize2']

# Cell
from fastai2.basics import *

# Cell
class TaskLabels(TensorBase): pass

# Cell
class Categorize2(Categorize):
    def encodes(self, o): return TaskLabels([self.vocab.o2i[o_] for o_ in o])
    def decodes(self, o): return [Category(self.vocab[o_]) for o_ in o]