# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_text.core.ipynb (unless otherwise specified).

__all__ = ['Tokens']

# Cell
from fastai2.text.all import *

# Cell
class Tokens(L): pass

# Cell
@patch
def __call__(self:Tokenizer, x, **kwargs):
    return retain_type(super(Tokenizer, self).__call__(x, **kwargs), typ=Tokens)