# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_text.labellers.ipynb (unless otherwise specified).

__all__ = ['WordLabeller']

# Cell
from fastai2.text.all import *
from ..basics import *

# Cell
def WordLabeller(words, label):
    def _inner(x:str):
        for w in L(words):
            if w in x: return label
    return TypeDispatch2([_inner])