# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AttrProxy": "00_core.ipynb",
         "maintain_labels": "00_core.ipynb",
         "Pipeline.__init__": "00_core.ipynb",
         "Labeller": "00_core.ipynb",
         "CategorizeTaskLabels": "01_data.transforms.ipynb",
         "MajorityLabelVoter": "03_model.majority_label_voter.ipynb",
         "Tokens": "05_text.core.ipynb",
         "Tokenizer.__call__": "05_text.core.ipynb",
         "WordLabeller": "06_text.labellers.ipynb"}

modules = ["core.py",
           "data/transforms.py",
           "models/majority_label_voter.py",
           "text/core.py",
           "text/labellers.py"]

doc_url = "https://lgvaz.github.io/pigboat/"

git_url = "https://github.com/lgvaz/pigboat/tree/master/"

def custom_doc_links(name): return None
