# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TypeDispatch2": "00_core.ipynb",
         "DispatchReg2": "00_core.ipynb",
         "typedispatch2": "00_core.ipynb",
         "reduce_lbls": "00_core.ipynb",
         "TaskLabels": "00_core.ipynb",
         "compose_tfms2": "00_core.ipynb",
         "Pipeline2": "00_core.ipynb",
         "register_categories": "00_core.ipynb",
         "ABSTAIN": "00_core.ipynb",
         "categorize": "00_core.ipynb",
         "MajorityLabelVoter": "03_model.majority_label_voter.ipynb"}

modules = ["core.py",
           "models/majority_label_voter.py"]

doc_url = "https://lgvaz.github.io/pigboat/"

git_url = "https://github.com/lgvaz/pigboat/tree/master/"

def custom_doc_links(name): return None
