# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core_old.ipynb (unless otherwise specified).

__all__ = ['TaskLabels']

# Cell
from fastai2.basics import *
from fastai2.text.all import Tokenizer

# Cell
# TODO: Implement show
class TaskLabels(TensorBase):
    def show(self, ctx=None, **kwargs): return str([categorize.decode(o) for o in self])